# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "br"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  - AgeCalculatorPlugin:
      nathalia: 26/08/1998
      leandro: 08/09/1997

# Google Analytics tracking id
google_analytics_id: G-DV5PGV5TJ9

# HTML Title
title: "NatilÃª Gourmet"

# Avatar image path
avatar: "./images/logo.png"

# Name section text
name: "NatilÃª"

# Tagline section text
tagline: >-
    Em breve sobremesas prÃ³ximo a vocÃª!
    <br>ğŸ“ SacolÃ©s Gourmet ğŸ›µ Delivery
    <br><a href='#onde-entregamos'>ğŸ“ Campo Grande - RJ</a>

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      id: "cardapio"
      icon: "fa-solid fa-cart-shopping"
      text: "CardÃ¡pio <span class='link-button-text'>(Com desconto!)</span>"
      url: "http://cardapio.natile.com.br"
      alt: "Link para o cardÃ¡pio no nosso site"
      title: "Link para o cardÃ¡pio no nosso site"
      target: "_self"
  - link:
      id: "ifood"
      icon: "fa-brands fa-ifood"
      text: "iFood"
      url: "http://ifood.natile.com.br"
      alt: "Link para o cardÃ¡pio no iFood"
      title: "Link para o cardÃ¡pio no iFood"
      target: "_blank"
  - button:
      id: "onde-entregamos"
      icon: "fa-solid fa-map"
      text: "Onde entregamos"
      alt: "Imagem ilustrativa de onde entregamos, na Ã¡rea central de Campo Grande - RJ"
      title: "Onde entregamos"
      content: >-
        <div class="warn"><i class="fa-solid fa-triangle-exclamation"></i><span>Cobertura inicialmente limitada. Demais localidades nos mande uma mensagem. â¤ï¸</span></div>
        <div id="cobertura-map"></div>
  - button:
      id: "sobre-nos"
      icon: "fa-solid fa-circle-info"
      text: "Sobre nÃ³s"
      alt: "Sobre nÃ³s"
      title: "Sobre nÃ³s"
      content: >-
        <img src="./images/sobre_nos.jpg"></img>
        <p>Oi, nÃ³s somos Nathalia e Leandro, temos {{vars.AgeCalculatorPlugin['nathalia']}} e {{vars.AgeCalculatorPlugin['leandro']}} anos, juntos
        decidimos em criar nossa primeira marca, a NatilÃª.<br>
        Juntamos nossa paixÃ£o por sobremesas geladas, artesanais e com
        um toque de ingredientes naturais, nascendo assim a nossa parceria entre Nath e LÃª (pegou a referÃªncia? ğŸ˜œ).</p>



# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-facebook"
      url: "http://facebook.natile.com.br"
      title: "Facebook"
      alt: "Facebook"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "http://instagram.natile.com.br"
      title: "Instagram"
      alt: "Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-tiktok"
      url: "http://tiktok.natile.com.br"
      title: "Tiktok"
      alt: "Tiktok"
      target: "_blank"
  - social:
      icon: "fa-brands fa-whatsapp"
      url: "http://whatsapp.natile.com.br"
      title: "Whatsapp"
      alt: "Whatsapp"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:contato@natile.com.br"
      title: "Email: contato@natile.com.br"
      alt: "contato@natile.com.br"
      target: "_blank"

# Footer text
footer: >
    Siga-nos nas redes sociais

# Footer copyright message
copyright: >
  Â© 2025 NatilÃª
